### ISSUE TITLE
ERROR CreateChatCompletionBlockModeAsync

### ISSUE THREAD

**Issue by JayWist** [IcedMango/DifyAi-csharp-sdk#13]
Please help check below exception, Thanks.

dify version:  **0.6.8**

DifyApi Request Failed! Response is not a validjson. Message: Unexpected character encountered while parsing value:<. Path '', line 0,position 0.

![image](https://github.com/IcedMango/DifyAi-csharp-sdk/assets/18067235/80302df4-21f5-4e97-92d8-846dcdd72474)

**Comment by IcedMango** [comment]
SDK version?

**Comment by JayWist** [comment]
> SDK version?

1.1.6

**Comment by IcedMango** [comment]
Published a new package, version 1.1.7. You can see the unmodified response text in the console.

**Comment by JayWist** [comment]
I was missing a slash...Thanks for your help~
![1718172467938](https://github.com/IcedMango/DifyAi-csharp-sdk/assets/18067235/d0662bc1-a54e-40dd-a359-79c8e709c93e)

![1718172496841](https://github.com/IcedMango/DifyAi-csharp-sdk/assets/18067235/ab06c9eb-817c-4016-8752-2d0a833e0a38)
